name: Remove needs-ok-to-test

on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [labeled]

jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        if: ${{ (github.event.label.name == 'needs-ok-to-test') && (github.event.pull_request.user.login == 'github-actions[bot]') }}
        with:
          labels: |
            needs-ok-to-test
